sudo: required
services:
- docker
before_install:
- docker build -t $DOCKER_IMAGE .
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
- docker push $DOCKER_IMAGE
script:
- docker run -it --rm $DOCKER_IMAGE py.test
- docker run -it --rm -e HALO_API_KEY=$HALO_API_KEY -e HALO_API_SECRET_KEY=$HALO_API_SECRET_KEY
  -e HALO_API_HOSTNAME=$HALO_API_HOSTNAME -e HALO_API_PORT=$HALO_API_PORT -e HALO_AGENT_KEY=$HALO_AGENT_KEY
  -e SERVER_GROUP=$SERVER_GROUP $DOCKER_IMAGE /app/scan_with_halo.sh
env:
  global:
  - SERVER_GROUP=dondash
  - HALO_API_HOSTNAME=api.cloudpassage.com
  - HALO_API_PORT=443
  - DOCKER_IMAGE="docker.io/berretterry/dondash"
  - secure: kHTO8w3cjM3cljUsrtAqZtWzYQFA//t6gb47P8ZHR5O/XIj3mPQ8TmzhMkTZXZMyejJkAmp2jWHqSe1qKuqtFChVflwJt5+l69nedl6xPHPR3s+y4SAHFRMDLAmwsYLwjA5k3v9CVxMOa2A7LeBd7bNoD8HNT0QAOMsOvToyb8DlTdHUDFHjKHNSZwGdTgosIKmUYWnABlWahbX45VN8ZjgFuFWmzgS0iu4s6iPVZ/yY7wagWn04wtSmFr04Hk7xXkct25ocVzhvQ8dIFoJHeaqhUq/EaWdx9p3NL3dPY1K/QV7BSrF5GtKmFgvJfPElDCIocsJMW60DEyEvRU/krH/7HDJXvWMi5H4cfS1bx4lnTZVLFFTk7O63QyRwpasmX4U1kAo7BvK95uDMB3m0ghqifVJXChA1NbTWJtwqO/uCnhnFry+KlqeI/ao8V7xDITKV8a79L+qMoyTOkJhH/wSw8JWY4J7GvOHJN9UIRwHP3pfE5KxBuZ5fux8HH8xlbKtviXv1jRBRupzbJDNiPobb9ZmIIdS0H7lN58Q/oB7K7XBBczzycyzKG3zlBx0Or6uhIIbC0cBoopL2cmOga37VnUDmbgNQYM8jeROkBs+x0ztvkxKhQz3oct6XvRjEgcQuXQuJlx48XXVC0vmzM3PAvwuYEoyYKU9/HOfhbM8=
